INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('W3 School','https://www.w3schools.com/js/default.asp', 'Encylopedia of HTML and Tutorial', 1, 4, 'https://www.ionos.com/digitalguide/fileadmin/DigitalGuide/Teaser/html-tagst.jpg' );
INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('W3 School','https://www.w3schools.com/css/css_intro.asp', 'CSS Introduction', 2, 2, 'https://pixelmechanics.com.sg/wp-content/uploads/2019/04/css.jpg');
INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('Javascript 30','https://javascript30.com/', 'Perfect for practicing Javascript!', 3, 3, 'https://cdn.sanity.io/images/1md8nkn2/production/03c0782f85b59270bc4b80ed1c43ca1d922c1f66-1280x720.jpg?w=2880&h=1620&fit=crop');
INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('Learn to Git Hubs','https://www.udemy.com/course/git-github-the-complete-git-github-course/?utm_source=adwords-learn&utm_medium=udemyads&utm_campaign=DSA_CA_Tech&utm_content=deal4584&utm_term=_._ag_76808851365_._ad_623904154958_._de_c_._dm__._pl__._ti_dsa-1011816637112_._li_1002283_._pd__._&gclid=CjwKCAjw44mlBhAQEiwAqP3eVhAnvN3Ytgkwxh__w_VW6E_61kDp9xZFBrUtu4sTQVhSlOAmPgbNtxoCJxYQAvD_BwE', 'A complete github course with videos', 4, 1,'https://d3mxt5v3yxgcsr.cloudfront.net/courses/8513/course_8513_image.jpg?v=1.0');
INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('W3 School','https://www.w3schools.com/js/default.asp', 'Encylopedia of HTML and Tutorial', 1, 4, 'https://www.lifeinnorway.net/wp-content/uploads/2023/02/northern-lights-photographer-with-gear-image.jpg' );
INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('W3 School','https://www.w3schools.com/css/css_intro.asp', 'CSS Introduction', 2, 2, 'https://pixelmechanics.com.sg/wp-content/uploads/2019/04/css.jpg');
INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('Javascript 30','https://javascript30.com/', 'Perfect for practicing Javascript!', 3, 3, 'https://cdn.sanity.io/images/1md8nkn2/production/03c0782f85b59270bc4b80ed1c43ca1d922c1f66-1280x720.jpg?w=2880&h=1620&fit=crop');

INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('Learn to Git Hubs','https://www.udemy.com/course/git-github-the-complete-git-github-course/?utm_source=adwords-learn&utm_medium=udemyads&utm_campaign=DSA_CA_Tech&utm_content=deal4584&utm_term=_._ag_76808851365_._ad_623904154958_._de_c_._dm__._pl__._ti_dsa-1011816637112_._li_1002283_._pd__._&gclid=CjwKCAjw44mlBhAQEiwAqP3eVhAnvN3Ytgkwxh__w_VW6E_61kDp9xZFBrUtu4sTQVhSlOAmPgbNtxoCJxYQAvD_BwE', 'A complete github course with videos', 4, 1,'https://d3mxt5v3yxgcsr.cloudfront.net/courses/8513/course_8513_image.jpg?v=1.0');
INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('SQL Tutorial', 'https://www.sqltutorial.org/', 'Comprehensive SQL tutorial for beginners', 5, 2, 'https://techcrunch.com/wp-content/uploads/2022/12/GettyImages-537331500.jpg?w=730&crop=1');
INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('Jest Testing Framework', 'https://jestjs.io/', 'A delightful JavaScript Testing Framework', 6, 3, 'https://assets.newatlas.com/dims4/default/57372fb/2147483647/strip/true/crop/2000x1335+0+0/resize/2000x1335!/quality/90/?url=http%3A%2F%2Fnewatlas-brightspot.s3.amazonaws.com%2F8a%2F13%2F564870064cf4b1deeac423436bcd%2Fdepositphotos-151972082-l-2015.jpg');
INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('DevDocs', 'https://devdocs.io/', 'A comprehensive web development documentation', 7, 4, 'https://www.peru.travel/Contenido/AcercaDePeru/Imagen/en/6/0.0/Principal/Machu%20Picchu.jpg');

INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('MDN Web Docs - HTML', 'https://developer.mozilla.org/en-US/docs/Web/HTML', 'Mozilla Developer Network - HTML documentation', 1, 1, 'https://media.blogto.com/uploads/2021/08/27/1630094748-20212508-ForestCafe-17.jpg?w=1400&cmd=resize&height=2500&quality=70');
INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('CSS Tricks', 'https://css-tricks.com/', 'Tips, Tricks, and Techniques on using CSS', 2, 3, 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Roasted_coffee_beans.jpg');

INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('MDN Web Docs - JavaScript', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript', 'Mozilla Developer Network - JavaScript documentation', 3, 2, 'https://www.thoughtco.com/thmb/094YF3bQBiuV_13n92GFQZWkM7k=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/JavaScript-58acbb8a3df78c345bad32c2.jpg');
INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('Google Fonts', 'https://fonts.google.com/', 'Collection of free and open-source web fonts', 7, 3, 'https://cdn.mos.cms.futurecdn.net/WvrMVKojxizRpgXPGwdNf.jpg');
INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('HTML Dog', 'https://www.htmldog.com/', 'HTML tutorials and references', 1, 2, 'https://www.nylabone.com/-/media/project/oneweb/nylabone/images/dog101/activities-fun/10-great-small-dog-breeds/maltese-portrait.jpg');
INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('CSS Grid Layout', 'https://cssgrid.io/', 'Learn CSS Grid Layout through practical examples', 2, 3, 'https://viget.imgix.net/2-dimensional.jpg?auto=format%2Ccompress&crop=focalpoint&fit=crop&fp-x=0.5&fp-y=0.5&ixlib=php-2.1.1&q=90&w=1280&s=04778b775e629740d44b152af71635f5');
INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('SVN Tutorial', 'https://www.atlassian.com/git/tutorials/svn-to-git-prepping-your-team-migration', 'Migrate from SVN to Git with this step-by-step tutorial', 4, 1, 'https://www.tutorialspoint.com/basics_of_computer_science/images/computer_networking.jpg');
INSERT INTO resources (title, url, description, category_id, user_id, photo_url) VALUES ('MongoDB Documentation', 'https://docs.mongodb.com/', 'Official documentation for MongoDB', 5, 2, 'https://www.turing.com/blog/wp-content/uploads/2022/02/Mongo-DB-Features.jpg');


